language: node_js
node_js: "8"

deploy:
  provider: s3
  access_key_id: "AKIAJQVWOER2UGVDXHBQ"
  secret_access_key: "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"
  bucket: "audius-releases"
  skip_cleanup: true
  acl: public_read
  region: ap-south-1
  local_dir: dist
  upload-dir: travis-builds

before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -rf win-unpacked mac *.blockmap ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -rf linux-unpacked *.blockmap ; fi

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - osx
  - linux

osx_image: xcode9.3

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then build --linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then build --mac --win; fi
