# Configuration file Travis CI
# Author - Mihir Pathak
#
# Consists of 4 jobs -
#   - 2 for master branch invoked only when tags are pushed
#   - 2 for dev branch and will be invoked for each push

# Build with Node JS 8 [9+ causes fsevetns build to crash in darwin]
language: node_js
node_js: "8"

# Job for building
jobs:
  include:
    - if: branch = master
      if: tag IS present
      os: linux
      dist: trusty
    - if: branch = master
      if: tag IS present
      os: osx
      osx_image: xcode9.3
    - if: branch = dev
      os: linux
      dist: trusty
    - if: branch = dev
      os: osx
      osx_image: xcode9.3

# S3 Deploy [builds can be found in audius-releases/automated-builds]
deploy:
  provider: s3
  access_key_id: "AKIAJQVWOER2UGVDXHBQ"
  secret_access_key: "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"
  bucket: "audius-releases"
  skip_cleanup: true
  acl: public_read
  region: ap-south-1
  local_dir: dist
  upload-dir: $UPLOAD_DIR
  on:
    all_branches: true

# Clean dist/ before uploading
before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -rf dist/win-unpacked/ dist/mac/ dist/*.blockmap ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -rf dist/linux-unpacked/ dist/*.blockmap ; fi
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then export UPLOAD_DIR="stable" ; fi
  - if [[ "$TRAVIS_BRANCH" == "dev" ]]; then export UPLOAD_DIR="test-builds" ; fi

# Global environment variables
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

# Cache directorries
cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

# Perform build [win32's exe and darwin's dmg in osx and linux's deb in linux]
script:
  - echo "Compiling React app for production [CI]"
  - yarn build-ci
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      echo "Packaging Audius for Linux x64 (.deb)";
      yarn package-linux;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "Packaging Audius for MacOS X (.dmg)";
      yarn package-mac;
      echo "Packaging Audius for Windows x64 (.exe)";
      yarn package-win;
    fi
  - echo "Writing current tag name to dist/LATEST"
  - echo "$TRAVIS_TAG" > dist/LATEST

after_success:
  - echo "Build completed and artifacts uploaded to S3 bucket"
