# Configuration file Travis CI
# Author - Mihir Pathak
#
# Consists of 2 jobs -
#   - Ubuntu bionic environment builds for Linux
#   - OSX builds for Mac

# Language configs
language: node_js
node_js: "10"

# Job for building
jobs:
  include:
    - if: tag IS present
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - python3-pip
            - python3-setuptools
    - if: tag IS present
      os: osx
      addons:
        homebrew:
          packages:
            - python3

# Run the build script depending on OS
script:
  - echo "Installing yarn dependencies"
  - yarn install
  
  - echo "Building raindow"
  - cd bin/rainbow
  - pip3 install --upgrade --user pip setuptools wheel
  - pip3 install --upgrade --user -r requirements.txt
  - pyinstaller rainbow.py
  - cd ../../
  
  - echo "Compiling React app for production"
  - yarn build
  
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      echo "Packaging Audius for Linux x64 (AppImage)";
      yarn package:linux;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "Packaging Audius for MacOS X (DMG)";
      yarn package:mac;
    fi

after_success:
  - echo "Build completed, uploaded artifacts (if any)"
