language: node_js
node_js: "9"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - osx
  - linux

osx_image: xcode9.3

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then build --linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then build --mac --win; fi
