os: linux
language: node_js
node_js: "9"

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then build --linux --win; fi
