# Configuration file Travis CI
# Author - Mihir Pathak
#
# Consists of 2 jobs -
#   - Linux environment builds for debian
#   - OSX builds for Mac and Windows

# Build with Node JS 8 [9+ causes fsevetns build to crash in darwin]
language: node_js
node_js: "8"

# Job for building
jobs:
  include:
    - if: tag IS present
      os: linux
      dist: trusty
    - if: tag IS present
      os: osx
      osx_image: xcode9.3

# Global environment variables
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

# Cache directorries
cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

# Perform build [win32's exe and darwin's dmg in osx and linux's deb in linux]
script:
  - echo "Initializing app files..."
  - yarn init-app
  - echo "Compiling React app for production"
  - yarn build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      echo "Packaging Audius for Linux x64 (.deb)";
      chmod a+x bin/ffmpeg/linux/ffmpeg;
      chmod a+x bin/rainbow/linux/rainbow;
      yarn package-linux;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "Packaging Audius for MacOS X (.dmg)";
      chmod a+x bin/ffmpeg/darwin/ffmpeg;
      chmod a+x bin/rainbow/darwin/rainbow;
      yarn package-mac;
      echo "Packaging Audius for Windows x64 (.exe)";
      yarn package-win;
    fi

after_success:
  - echo "Build completed, uploaded artifacts (if any)"
