language: node_js
node_js: "8"

addons:
  artifacts:
    paths:
      - $(ls dist/*.dmg | tr "\n" ":")
      - $(ls dist/*.exe | tr "\n" ":")
      - $(ls dist/*.deb | tr "\n" ":")

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - ARTIFACTS_KEY="AKIAJQVWOER2UGVDXHBQ"
    - ARTIFACTS_SECRET="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"
    - ARTIFACTS_BUCKET="audius-releases"
    - ARTIFACTS_REGION="ap-south-1"

os:
  - osx
  - linux

osx_image: xcode9.3

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then build --linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then build --mac --win; fi
