# Configuration file Travis CI
# Author - Mihir Pathak
#
# Consists of 3 jobs -
#   - Ubuntu bionic environment builds for Linux
#   - OSX builds for Mac
#   - Windows that does nothing

# Language configs
language: node_js
node_js: "10"

# Job for building
jobs:
  include:
    - if: tag IS present
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - python3-pip
            - python3-setuptools
    - if: tag IS present
      os: osx
      addons:
        homebrew:
          taps:
            - sashkab/python
          packages:
            - python36
    - if: tag IS present
      os: windows

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      # Install Python 3.6 from Chocolately
      choco install python --version 3.6.7
      refreshenv
      

      # Disable windows defender :3
      export NODEPATH=$(where.exe node.exe)
      export PROJECTDIR=$(pwd)
      export YARNCACHE=$(yarn cache dir)
      export TEMPDIR=$LOCALAPPDATA\\Temp

      powershell Add-MpPreference -ExclusionProcess ${NODEPATH}
      powershell Add-MpPreference -ExclusionPath ${YARNCACHE}
      powershell Add-MpPreference -ExclusionPath ${PROJECTDIR}
      powershell Add-MpPreference -ExclusionPath ${TEMPDIR}

      echo "DisableArchiveScanning..."
      powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableArchiveScanning \$true'"

      echo "DisableBehaviorMonitoring..."
      powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableBehaviorMonitoring \$true'"

      echo "DisableRealtimeMonitoring..."
      powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableRealtimeMonitoring \$true'"
    fi
  - |
    cd bin/rainbow
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      echo "Windows builds coming soon!"
    else
      pip3 install --upgrade --user pip setuptools wheel
      pip3 install --upgrade --user -r requirements.txt
      python3 setup.py build
    fi
    cd ../

# Run the build script depending on OS
script:
  - echo "Compiling React app for production"
  - yarn build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    echo "Packaging Audius for Linux x64 (AppImage)";
      yarn package:linux;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "Packaging Audius for MacOS X (DMG)";
      yarn package:mac;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      echo "Doing nothing";
    fi

after_success:
  - echo "Build completed, uploaded artifacts (if any)"
