image: Visual Studio 2015

environment:
  PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%/Scripts/pip.exe install -U -r bin/rainbow/requirements.txt"
  - "yarn install"

build_script:
  - "%PYTHON%/python.exe bin/rainbow/setup.py build"
  - "yarn build"
  - "yarn package:win"

artifacts:
  - path: dist/AudiusSetup-x64.exe
