image: Visual Studio 2015

environment:
  PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%/Scripts/pip.exe install -U -r requirements.txt"
  - "yarn install"

build_script:
  - "%PYTHON%/Scripts/pyinstaller.exe rainbow.py"
  - "yarn build"
  - "yarn package:win"

artifacts:
  - path: dist/AudiusSetup-x64.exe
